logging.level.root=WARN
management.endpoints.web.exposure.include=health,info
server.error.include-message=never
server.error.include-binding-errors=never

# The default database change as sqlite, original database as postgresql or mysql should work when provide
spring.datasource.url=${DB_URL:jdbc:sqlite:comp4442.db}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.sqlite.JDBC}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}


jwt.private-key-path=${JWT_PRIVATE_KEY_PATH:file:/opt/cloud-compute/cert/ECDSA_384_private.pem}
jwt.public-key-path=${JWT_PUBLIC_KEY_PATH:file:/opt/cloud-compute/cert/ECDSA_384_public.pem}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

file.upload.max-size-bytes=${FILE_UPLOAD_MAX_SIZE_BYTES:5242880}
file.scan.enabled=${FILE_SCAN_ENABLED:false}
file.scan.docker-image=${FILE_SCAN_DOCKER_IMAGE:clamav/clamav:stable}
file.scan.timeout-seconds=${FILE_SCAN_TIMEOUT_SECONDS:30}
