spring.application.name=cloud-compute-service
server.port=8080
management.endpoints.web.exposure.include=health,info
spring.profiles.active=dev
server.error.include-message=never
server.error.include-binding-errors=never
spring.jackson.time-zone=UTC


jwt.private-key-path=classpath:cert/ECDSA_384_private.pem
jwt.public-key-path=classpath:cert/ECDSA_384_public.pem
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.max-size-bytes=5242880
file.scan.enabled=false
file.scan.docker-image=clamav/clamav:stable
file.scan.timeout-seconds=30

# Log file name & path (logs will save to project folder: logs/app.log)
logging.file.name=logs/app.log
# Log level: root info, your project package debug
logging.level.root=INFO
logging.level.hk.polyu.comp4442.cloudcompute=DEBUG
# Log format (match your project needs)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Rolling log: max size per file = 10MB, max history 30 days
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
