logging.level.root=INFO
logging.level.hk.polyu.comp4442=DEBUG



spring.datasource.url=jdbc:sqlite:comp4442.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=sa
spring.datasource.password=


jwt.private-key-path=classpath:cert/ECDSA_384_private.pem
jwt.public-key-path=classpath:cert/ECDSA_384_public.pem


spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=false

spring.jpa.show-sql=true
