logging.level.root=WARN
management.endpoints.web.exposure.include=health,info

# The default database change as sqlite, original database as postgresql or mysql should work when provide
spring.datasource.url=${DB_URL:jdbc:sqlite:comp4442.db}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.sqlite.JDBC}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}


jwt.private-key-path=${JWT_PRIVATE_KEY_PATH}
jwt.public-key-path=${JWT_PUBLIC_KEY_PATH}

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
