spring.application.name=cloud-compute-service
server.port=8080
management.endpoints.web.exposure.include=health,info
spring.profiles.active=dev
server.error.include-message=never
server.error.include-binding-errors=never
spring.jackson.time-zone=UTC


jwt.private-key-path=classpath:cert/ECDSA_384_private.pem
jwt.public-key-path=classpath:cert/ECDSA_384_public.pem
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.max-size-bytes=5242880
file.scan.enabled=false
file.scan.docker-image=clamav/clamav:stable
file.scan.timeout-seconds=30
