spring.application.name=cloud-compute-service
server.port=8080
management.endpoints.web.exposure.include=health,info
spring.profiles.active=dev
server.error.include-message=always
server.error.include-binding-errors=always
spring.jackson.time-zone=UTC
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
